### ISSUE TITLE
getting it to work

### ISSUE THREAD

**Issue by mezod** [shakacode/bootstrap-sass-loader#33]
Hi, I am having some trouble to get it to work,
I first installed bootstrap-sass-loader
`
npm install --save bootstrap-sass-loader
`
which also installed bootstrap-sass.

Then I added 
`
require('bootstrap-sass-loader');
`
to my index.js.

I want to use the full bootstrap, so I don't need to customize it. However, this doesn't seem to work when I define a
`
<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
`

I added
```
{
      test: /bootstrap\/js\//,
      loader: 'imports?jQuery=jquery',
    },
    {
      test: /\.woff(\?v=\d+\.\d+\.\d+)?$/,
      loader: 'url?limit=10000&mimetype=application/font-woff',
    },
    {
      test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/,
      loader: 'url?limit=10000&mimetype=application/font-woff',
    },
    {
      test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
      loader: 'url?limit=10000&mimetype=application/octet-stream',
    },
    {
      test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
      loader: 'file',
    },
    {
      test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
      loader: 'url?limit=10000&mimetype=image/svg+xml',
    }
```
to my webpack config, with no luck. Am I missing something here? Thanks!

**Comment by justin808** [comment]
@mezod Please see how we're using this here:

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/webpack.client.hot.config.js

And please keep me posted on getting this solved.

**Comment by mezod** [comment]
thanks, apparently I was doing it alright but I had corrupted packages... rm -rf node_modules + npm install and it worked as supposed to :-)
