### ISSUE TITLE
"1.a Complete Bootstrap" not working for me

### ISSUE THREAD

**Issue by BrendanBerkley** [shakacode/bootstrap-sass-loader#39]
I'm learning Webpack, so this is probably pretty basic stuff.

Thought I'd start by trying to get Bootstrap working, so I found this repo and gave it a try. Added `require("bootstrap-sass-loader");` to my `entry.js` file and run `webpack-dev-server`. Get this output:

```bash
http://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from /home/brendan/Projects/passit-proto
Hash: 1be5be6dbbcbf9ba03ed
Version: webpack 1.12.9
Time: 108ms
    Asset     Size  Chunks             Chunk Names
bundle.js  2.94 kB       0  [emitted]  main
chunk    {0} bundle.js (main) 1.39 kB [rendered]
    [0] ./entry.js 104 bytes {0} [built]
    [1] ./~/bootstrap-sass-loader/index.js 54 bytes {0} [built]
    [2] ./~/bootstrap-sass-loader/bootstrap-sass-no-customizations.config.js 1.23 kB {0} [built]
webpack: bundle is now VALID.
```

Here's my `webpack.config.js` file:

```javascript
module.exports = {
    entry: "./entry.js",
    output: {
        path: __dirname,
        filename: "bundle.js"
    }
};
```

No errors on build, and I'm pretty sure everything is wired up correctly in terms of paths because if I look at `bundle.js`, it shows the contents of `bootstrap-sass-no-customizations.config.js`

But when I load up http://localhost:8080, I don't see any evidence that anything other than that config file was loaded. No evidence of Sass or the actual JS files being placed.

Am I missing a step here? Any help is appreciated.

**Comment by alexfedoseev** [comment]
Hi @BrendanBerkley, `bootstrap-sass-loader` will be deprecated soon in favour of  `bootstrap-loader`. Please try it out. Here is the link to the docs: https://github.com/shakacode/bootstrap-loader/tree/alex/bootstrap-4

**Comment by justin808** [comment]
Please see the links here: http://forum.shakacode.com/t/open-source-help-wanted/416

That has a list to the new loaders.
