### ISSUE TITLE
Feature request: Ability to turn off scripts and dependency on jquery

### ISSUE THREAD

**Issue by positron** [shakacode/bootstrap-sass-loader#40]
I'm aware that I can opt out of the scripts by setting every script to `false` in `bootstrap-sass.config.js` but the result still depends on jQuery, which I do not need.

**Comment by justin808** [comment]
Hi @positron I agree this is an issue, and I'd happily merge in a pull request.

We're extremely busy getting the successor to this ready:

Please see the links here: http://forum.shakacode.com/t/open-source-help-wanted/416

@positron if you can post some more info, I can help you with making this one work.

**Comment by positron** [comment]
It looks like bootstrap-loader 0.0.5 does what I want, thanks!
