### ISSUE TITLE
bootstrap-sass-loader with eslint-loader

### ISSUE THREAD

**Issue by AllenFang** [shakacode/bootstrap-sass-loader#42]
Hi, I got the following errors with eslint-loader
```
ERROR in ./~/bootstrap-sass-loader/bootstrap-sass-scripts.loader.js!./app/styles/bootstrap-sass.config.js
Module build failed: Error: Cannot find module '/Users/allen/Node/react-universal-wafer-demo/node_modules/eslint-loader/index.js!/Users/allen/Node/react-universal-wafer-demo/app/styles/bootstrap-sass.config.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
   ....
```
and this is my module configuration in webpack
```js
module: {
    preLoaders: [
      { test: JS_REGEX, exclude: /(node_modules)/, loader: 'eslint' }
    ],
    loaders: [
      { test: JS_REGEX, exclude: /(node_modules)/, loader: 'babel' }
    ]
}
```
Currently, a workaround is to exclude bootstrap-sass.config when webpack loading
Anyway, I use <code>bootstrap-sass@3.3.6</code> and <code>bootstrap-sass-loader@1.0.9</code> and I'm sure the path of <code>bootstrap-sass.config.js</code> is correct, so any idea?
Thanks

**Comment by alexfedoseev** [comment]
@AllenFang Please try [`bootstrap-loader`](https://github.com/shakacode/bootstrap-loader). This is rewritten version of `bootstrap-sass-loader` (which will be deprecated). If issue will still occur, please transfer it to `bootstrap-loader` repo, and we will solve it there. Thanks!

**Comment by AllenFang** [comment]
@alexfedoseev, thanks for quickly response, I'll try <code>bootstrap-loader</code> :+1:
