### ISSUE TITLE
How can I access bootstrap variables?

### ISSUE THREAD

**Issue by vjpr** [shakacode/bootstrap-sass-loader#43]
I want to access variables like `$navbar-height` in stylesheets.

Is there a way to import all the customized variables?

In the docs I noticed it says:

> and your main Sass file that can depend on Bootstrap variables

This makes me think there is only one place I can depend on Bootstrap variables.

**Comment by justin808** [comment]
Hi @vjpr If you have one sass file, then so long as you defined the variable, you can see it.

By this, I mean, you need to put your sass in this config (name the file as you please). Then you can see all the bootstrap mixins, variables, etc.

```
  mainSass: "./main.scss", // path to your main SASS file (optional)
```

**Comment by vjpr** [comment]
I have a lots of sass files and they are required individually using webpack. I just want to import the variables. Sounds like it's not possible?

**Comment by justin808** [comment]
Hi @vjpr, that's not the way that sass works.

**Comment by vjpr** [comment]
It's how webpack loaders work. Each file is compiled into css. Then it is appended to the header in a style tag.

The way I am thinking is importing the bootstrap variables. Then importing the precustomization file with my modifications to the variables. Then I can access the variables.

**Comment by justin808** [comment]
@vjpr we're changing the way we're doing the assets parts as shown here: https://github.com/shakacode/react-webpack-rails-tutorial/

See our npm "sass-resources-loader"...

We'll have some more docs on this in the next couple of weeks.

The sass-resources loader will prepend any common definition files, which sounds like what you want!

**Comment by alexfedoseev** [comment]
@vjpr [`bootstrap-loader`](https://github.com/shakacode/bootstrap-loader) + [`sass-resources loader`](https://github.com/shakacode/sass-resources-loader) will solve it.

**Comment by vjpr** [comment]
So I have switched to bootstrap-loader and sass-resources-loader.

I now have a file called `variables.scss` referenced in `webpack.config.js` in `sassResources` which contains:

```
@import './pre-customizations.scss';
@import '../../node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss';
@import './customizations.scss';
```

This works well.

**Comment by alexfedoseev** [comment]
@vjpr Great, glad it helped :+1:

**Comment by damassi** [comment]
After looking high and low for a solution, `sass-resources-loader` did it. Might be worthwhile to add a note in the `bootstrap-loader` README. 👍

**Comment by justin808** [comment]
@damassi Any chance that you can give us a PR note to the README.md. @alexfedoseev and I would super appreciate it! We're slammed with our new product release.

**Comment by damassi** [comment]
Will do.
