### ISSUE TITLE
Style loader class name spaced

### ISSUE THREAD

**Issue by adrianmaurer** [shakacode/bootstrap-sass-loader#46]
I'm currently trying to figure out if there is a way to include the bootstrap library wrapped in a class selector. e.g.

```
.app {
  @import `bootstrap`;
}
```

The reason I'd like to do this is because the I'm retrofitting a react app into an existing app that has several wrapping elements that depend on the legacy app style sheets which use an older version of bootstrap and I'd like to avoid overriding conflicting styles.

Essentially I need to change this style loader to look something like
```
var start =
     ".app { "
     + "@import          \"~bootstrap/less/variables.less\";\n"
    + "@icon-font-path: \"~bootstrap/fonts/\";\n"
    + "@import          \"./bootstrap.config.less\";\n";
    + "}"
```

**Comment by justin808** [comment]
@adrianmaurer Can you please try using the https://github.com/shakacode/bootstrap-loader/.
